- http/커뮤니티 게시글 crud.http
- src/main/java/com/sparta/publicclassdev/domain/community/controller/CommunitiesController.java
- src/main/java/com/sparta/publicclassdev/domain/community/dto/CommunitiesUpdateRequestDto.java
- src/main/java/com/sparta/publicclassdev/domain/community/entity/Communities.java
- src/main/java/com/sparta/publicclassdev/domain/community/service/CommunitiesService.java
- src/main/java/com/sparta/publicclassdev/global/exception/ErrorCode.java
> ✨ feat : 커뮤니티 게시글 업데이트

- http/커뮤니티 게시글 crud.http
- src/main/java/com/sparta/publicclassdev/domain/community/controller/CommunitiesController.java
- src/main/java/com/sparta/publicclassdev/domain/community/service/CommunitiesService.java
#18 
✨ feat : 커뮤니티 게시글 삭제/조회 구현
>
> ✨ feat : 커뮤니티 게시글 삭제/조회 구현

- http/user.http
- src/main/java/com/sparta/publicclassdev/domain/community/repository/CommunitiesRepository.java
- src/main/java/com/sparta/publicclassdev/domain/users/controller/UsersController.java
- src/main/java/com/sparta/publicclassdev/domain/users/dto/ProfileRequestDto.java
- src/main/java/com/sparta/publicclassdev/domain/users/dto/ProfileResponseDto.java
- src/main/java/com/sparta/publicclassdev/domain/users/dto/UpdateProfileResponseDto.java
- src/main/java/com/sparta/publicclassdev/domain/users/entity/Users.java
- src/main/java/com/sparta/publicclassdev/domain/users/service/UsersService.java
> #이슈번호
> Close #12 
> 프로필 조회, 수정구현
>
> [2024-07-23] feat/#12-profile >> 프로필 조회, 수정구현

- http/커뮤니티 댓글.http
- src/main/java/com/sparta/publicclassdev/domain/community/service/CommunitiesService.java
- src/main/java/com/sparta/publicclassdev/domain/communitycomments/controller/CommunityCommentsController.java
- src/main/java/com/sparta/publicclassdev/domain/communitycomments/dto/CommunityCommentResponseDto.java
- src/main/java/com/sparta/publicclassdev/domain/communitycomments/dto/CommunityCommentsRequestDto.java
- src/main/java/com/sparta/publicclassdev/domain/communitycomments/entity/CommunityComments.java
- src/main/java/com/sparta/publicclassdev/domain/communitycomments/repository/CommunityCommentsRepository.java
- src/main/java/com/sparta/publicclassdev/domain/communitycomments/service/CommunityCommentsService.java
- src/main/java/com/sparta/publicclassdev/global/exception/ErrorCode.java
> ✨ feat : 커뮤니티 댓글 crud

- http/코드 리뷰.http
- src/main/java/com/sparta/publicclassdev/domain/likes/controller/LikesController.java
- src/main/java/com/sparta/publicclassdev/domain/likes/entity/Likes.java
- src/main/java/com/sparta/publicclassdev/domain/likes/repository/LikesRepository.java
- src/main/java/com/sparta/publicclassdev/domain/likes/service/LikesService.java
> #30 
- 코드 리뷰 게시글 댓글에 대해 좋아요 추가/삭제 기능 구현
>
> [2024.07.23] feat/#30 코드 리뷰 댓글 좋아요 기능

- src/main/java/com/sparta/publicclassdev/domain/codereview/dto/CodeReviewsDetailResponseDto.java
- src/main/java/com/sparta/publicclassdev/domain/codereview/dto/CodeReviewsListResponseDto.java
- src/main/java/com/sparta/publicclassdev/domain/codereview/dto/CodeReviewsWithUserResponseDto.java
- src/main/java/com/sparta/publicclassdev/domain/codereview/repository/CodeReviewsRepository.java
- src/main/java/com/sparta/publicclassdev/domain/codereview/service/CodeReviewsService.java
- src/main/java/com/sparta/publicclassdev/domain/codereviewcomment/dto/CodeReviewCommentsWithLikesResponseDto.java
- src/main/java/com/sparta/publicclassdev/domain/codereviewcomment/repository/CodeReviewCommentsRepository.java
> #14
> Close #14
- 코드 리뷰 게시글 조회 시 user 정보와 JOIN하여 조회
- 코드 리뷰 게시글 단건 조회 시 게시글 작성자 정보와 댓글관련 정보, 좋아요 수를 JOIN 하여 조회
>
> [2024.07.24] feat/#14 코드 리뷰 게시글 조회 Refactor

- src/main/java/com/sparta/publicclassdev/domain/community/dto/CommunitiesResponseDto.java
- src/main/java/com/sparta/publicclassdev/domain/community/entity/Communities.java
- src/main/java/com/sparta/publicclassdev/domain/community/service/CommunitiesService.java
- src/main/java/com/sparta/publicclassdev/domain/communitycomments/dto/CommunityCommentResponseDto.java
#40 
게시글 단건 조회시 작성자 이름, 댓글 추가 
>
> 🩹 fix : 게시글 단건 조회시 작성자 이름, 댓글 추가

- src/main/java/com/sparta/publicclassdev/domain/codereview/controller/CodeReviewsController.java
- src/main/java/com/sparta/publicclassdev/domain/codereview/dto/CodeReviewsSearchResponseDto.java
- src/main/java/com/sparta/publicclassdev/domain/codereview/repository/CodeReviewsRepository.java
- src/main/java/com/sparta/publicclassdev/domain/codereview/service/CodeReviewsService.java
> #41 
> Close #41
> - 코드 리뷰 게시글 카테고리 검색 기능 구현
> - 내림차순으로 정렬
>
> [2024-07-24] Feat/#41 코드 리뷰 게시글 카테고리 검색 기능 구현

- http/코드 리뷰.http
- src/main/java/com/sparta/publicclassdev/domain/codereview/service/CodeReviewsService.java
- src/main/java/com/sparta/publicclassdev/domain/codereviewcomment/service/CodeReviewCommentsService.java
> #47
> Close #47
> - 코드 리뷰 기능 (게시글, 댓글) ADMIN 권한은 모두 수정/삭제 할 수 있도록 권한 Refactor
>
> [2024-07-24] feat/#47 코드리뷰 기능 권한별 기능 Refactor

- src/main/java/com/sparta/publicclassdev/domain/codereview/dto/CodeReviewsDetailResponseDto.java
> #51
> Close #51
> -Code Review 게시글 단건 조회시 게시글 내용 필드 누락 추가
>
> [2024-07-25] refactor: Code Review 게시글 단건 조회시 게시글 내용 필드 누락 추가

- http/user.http
- src/main/java/com/sparta/publicclassdev/domain/users/controller/UsersController.java
- src/main/java/com/sparta/publicclassdev/domain/users/dto/PointRequestDto.java
- src/main/java/com/sparta/publicclassdev/domain/users/dto/PointResponseDto.java
- src/main/java/com/sparta/publicclassdev/domain/users/entity/CalculateTypeEnum.java
- src/main/java/com/sparta/publicclassdev/domain/users/entity/RankEnum.java
- src/main/java/com/sparta/publicclassdev/domain/users/entity/Users.java
- src/main/java/com/sparta/publicclassdev/domain/users/service/UsersService.java
> #이슈번호
> Close #50 
> 포인트, 등급 시스템 구현
>
> [2024-07-25] Feat/#50 point rank >> 포인트, 등급 시스템 구현

- build.gradle
- http/팀매칭.http
- src/main/java/com/sparta/publicclassdev/domain/chatrooms/controller/ChatRoomsController.java
- src/main/java/com/sparta/publicclassdev/domain/chatrooms/dto/ChatRoomsDto.java
- src/main/java/com/sparta/publicclassdev/domain/chatrooms/entity/ChatRoomUsers.java
- src/main/java/com/sparta/publicclassdev/domain/chatrooms/entity/ChatRooms.java
- src/main/java/com/sparta/publicclassdev/domain/chatrooms/entity/Messages.java
- src/main/java/com/sparta/publicclassdev/domain/chatrooms/repository/ChatRoomUsersRepository.java
- src/main/java/com/sparta/publicclassdev/domain/chatrooms/repository/ChatRoomsRepository.java
- src/main/java/com/sparta/publicclassdev/domain/chatrooms/repository/MessagesRepository.java
- src/main/java/com/sparta/publicclassdev/domain/chatrooms/service/ChatRoomsService.java
- src/main/java/com/sparta/publicclassdev/domain/teams/controller/TeamsController.java
- src/main/java/com/sparta/publicclassdev/domain/teams/dto/TeamResponseDto.java
- src/main/java/com/sparta/publicclassdev/domain/teams/entity/TeamUsers.java
- src/main/java/com/sparta/publicclassdev/domain/teams/entity/Teams.java
- src/main/java/com/sparta/publicclassdev/domain/teams/repository/TeamUsersRepository.java
- src/main/java/com/sparta/publicclassdev/domain/teams/repository/TeamsRepository.java
- src/main/java/com/sparta/publicclassdev/domain/teams/service/TeamsService.java
- src/main/java/com/sparta/publicclassdev/global/config/SchedulerConfig.java
- src/main/java/com/sparta/publicclassdev/global/config/WebSocketConfig.java
- src/main/java/com/sparta/publicclassdev/global/exception/ErrorCode.java
- src/test/java/com/sparta/publicclassdev/domain/chatrooms/service/ChatRoomsServiceTest.java
> #44 
> Close #44 
> - 팀 이름 랜덤 생성 구현
> - 팀 단건 조회
> - 실시간 채팅 구현
> - 실시간 채팅 확인은 프론트가 구현되야 함으로 테스트코드로만 작성 확인(추후 재확인 해야함)
>
> [Task] 팀 이름 랜덤 생성 및 실시간 채팅 구현 #44

- src/main/java/com/sparta/publicclassdev/domain/community/controller/CommunitiesController.java
- src/main/java/com/sparta/publicclassdev/domain/community/service/CommunitiesService.java
- src/main/java/com/sparta/publicclassdev/domain/communitycomments/service/CommunityCommentsService.java
#55 
게시글/댓글 작성자가 아닌 사용자 수정/삭제 못하도록 수정
>
> 🩹 fix : 게시글/댓글 사용자아닌 사용자 수정/삭제 못하도록 수정

- src/main/java/com/sparta/publicclassdev/domain/codereview/controller/CodeReviewsController.java
- src/main/java/com/sparta/publicclassdev/domain/codereview/service/CodeReviewsService.java
- src/main/java/com/sparta/publicclassdev/domain/codereviewcomment/controller/CodeReviewCommentsController.java
> #60
> Close #60
> - Code Reivew 기능 게시물, 댓글 메서드 이름 오타 수정
>
> [24-07-26]  fix/#60 메서드 이름 오타 수정

- src/main/java/com/sparta/publicclassdev/domain/community/component/CleanUpScheduler.java
- src/main/java/com/sparta/publicclassdev/domain/community/controller/CommunitiesController.java
- src/main/java/com/sparta/publicclassdev/domain/community/dto/CommunitiesRankDto.java
- src/main/java/com/sparta/publicclassdev/domain/community/service/CommunitiesService.java
- src/main/java/com/sparta/publicclassdev/global/config/RedisConfig.java
#43 
> 실시간 검색
> 30분마다 검색된 시간과 비교하여 검색 순위에서 삭제 하도록
>
> ✨ feat : 실시간 검색 순위 구현

- src/main/java/com/sparta/publicclassdev/domain/users/controller/UsersController.java
- src/main/java/com/sparta/publicclassdev/global/config/WebMvcConfig.java
> #이슈번호
> Close #68
> 토큰 발급위치를 헤더에서 바디로 변경
>
> [2024-07-29] refactor/#68-login-reissue-token >> 로그인, 토큰 재발급 코드 수정

- http/user.http
- src/main/java/com/sparta/publicclassdev/domain/users/controller/UsersController.java
- src/main/java/com/sparta/publicclassdev/domain/users/dto/PasswordRequestDto.java
- src/main/java/com/sparta/publicclassdev/domain/users/entity/Users.java
- src/main/java/com/sparta/publicclassdev/domain/users/service/UsersService.java
> #이슈번호
> Close #70 
> 프로필 수정과 비밀번호 초기화 분리
>
> [2024-07-29] refactor/#70-update-profile-reset-password >> 프로필 수정과 비밀번호 초기화 분리

- src/main/java/com/sparta/publicclassdev/domain/codereview/service/CodeReviewsService.java
> #72
> Close #72
> - 코드리뷰 게시글 파일 업로드, 다운로드 오류로 인한 로직 refactor
>
> [2024-07-30] refactor/#72 코드리뷰 게시글 파일 업로드, 다운로드 오류로 인한 로직 refactor

- src/main/java/com/sparta/publicclassdev/domain/codereview/service/CodeReviewsService.java
> #74 
> Close #74
> - 파일 업데이트 오류로 인한 로직 refactor
>
> [2024-07-30] refactor/#74 파일 업데이트 오류로 인한 로직 refactor

- http/user.http
- src/main/java/com/sparta/publicclassdev/global/config/WebMvcConfig.java
- src/main/java/com/sparta/publicclassdev/global/security/JwtAuthorizationFilter.java
- src/main/java/com/sparta/publicclassdev/global/security/JwtUtil.java
> #이슈번호
> Close #76 
> 토큰 만료시 상태코드와 메세지가 반환되도록 수정
>
> [2024-07-30] fix/#76-fix-to-return-statuscode-message >> 토큰 만료시 상태코드와 메세지가 반환되도록 수정

- http/코드 실행.http
- http/코드카타.http
- http/팀매칭.http
- src/main/java/com/sparta/publicclassdev/domain/coderuns/controller/CodeRunsController.java
- src/main/java/com/sparta/publicclassdev/domain/coderuns/dto/CodeRunsDto.java
- src/main/java/com/sparta/publicclassdev/domain/coderuns/dto/CodeRunsRequestDto.java
- src/main/java/com/sparta/publicclassdev/domain/coderuns/dto/CodeRunsResponseDto.java
- src/main/java/com/sparta/publicclassdev/domain/coderuns/entity/CodeRuns.java
- src/main/java/com/sparta/publicclassdev/domain/coderuns/repository/CodeRunsRepository.java
- src/main/java/com/sparta/publicclassdev/domain/coderuns/runner/CodeRunner.java
- src/main/java/com/sparta/publicclassdev/domain/coderuns/runner/JavaCodeRunner.java
- src/main/java/com/sparta/publicclassdev/domain/coderuns/runner/JavaScriptCodeRunner.java
- src/main/java/com/sparta/publicclassdev/domain/coderuns/runner/PythonCodeRunner.java
- src/main/java/com/sparta/publicclassdev/domain/coderuns/service/CodeRunsService.java
- src/main/java/com/sparta/publicclassdev/domain/teams/entity/Teams.java
- src/main/java/com/sparta/publicclassdev/global/exception/ErrorCode.java
> #67 
> Close #67 
> - 각 언어별 코드를 실행 후 가장 빠른 시간 db에 저장
>
> [Task] 각 언어별 코드 실행 구현

- src/main/java/com/sparta/publicclassdev/domain/codereview/controller/CodeReviewsController.java
> #79
> Close #79
> - Patch 에서 Put으로 변경
>
> [2024-07-30] refactor/#79 컨트롤러 HTTP 메서드 변경

- src/main/java/com/sparta/publicclassdev/domain/community/dto/CommunitiesResponseDto.java
- src/main/java/com/sparta/publicclassdev/domain/community/service/CommunitiesService.java
#83 
react에서 필요한 데이터때문에 response Dto 수정
ranking 범위 수정
>
> 🩹 fix : dto 수정 및 ranking 범위 수정

- src/main/java/com/sparta/publicclassdev/global/exception/GlobalExceptionHandler.java
> #이슈번호
> Close #85 
> 메세지와 상태코드가 출력되도록 수정
>
> [2024-07-30] fix/#85-task-validation-message validation >> 메세지와 상태코드가 출력되도록 수정

- src/main/java/com/sparta/publicclassdev/domain/community/controller/CommunitiesController.java
- src/main/java/com/sparta/publicclassdev/domain/community/repository/CommunitiesRepository.java
- src/main/java/com/sparta/publicclassdev/domain/community/service/CommunitiesService.java
#88 
검색 결과 페이지네이션을 프론트에서 해주는걸로 변경
>
> 🩹 fix : 검색 결과 페이지네이션을 프론트에서 해주는걸로 변경

- src/main/java/com/sparta/publicclassdev/domain/community/controller/CommunitiesController.java
- src/main/java/com/sparta/publicclassdev/domain/community/dto/CommunitiesRequestDto.java
- src/main/java/com/sparta/publicclassdev/domain/communitycomments/controller/CommunityCommentsController.java
- src/main/java/com/sparta/publicclassdev/domain/communitycomments/dto/CommunityCommentsRequestDto.java
> 🩹 fix : valid 수정

- http/코드 실행.http
- src/main/java/com/sparta/publicclassdev/domain/codekatas/entity/CodeKatas.java
- src/main/java/com/sparta/publicclassdev/domain/coderuns/repository/CodeRunsRepository.java
- src/main/java/com/sparta/publicclassdev/domain/teams/controller/TeamsController.java
- src/main/java/com/sparta/publicclassdev/domain/teams/repository/TeamUsersRepository.java
- src/main/java/com/sparta/publicclassdev/domain/teams/service/TeamsService.java
- src/main/java/com/sparta/publicclassdev/domain/winners/controller/WinnersController.java
- src/main/java/com/sparta/publicclassdev/domain/winners/dto/WinnersResponseDto.java
- src/main/java/com/sparta/publicclassdev/domain/winners/entity/Winners.java
- src/main/java/com/sparta/publicclassdev/domain/winners/repository/WinnersRepository.java
- src/main/java/com/sparta/publicclassdev/domain/winners/service/WinnersService.java
- src/main/java/com/sparta/publicclassdev/global/config/SchedulerConfig.java
- src/main/resources/logback-spring.xml
[Task] 명예의 전당 구현하기 #82
> #82 
> Close #82 
> - 명예의 전당 페이지 기능 구현 및 스케줄 구현
>
> [Task] 명예의 전당 구현하기 #82

- src/main/java/com/sparta/publicclassdev/domain/community/dto/CommunitiesResponseDto.java
- src/main/java/com/sparta/publicclassdev/domain/community/service/CommunitiesService.java
- src/main/java/com/sparta/publicclassdev/domain/communitycomments/dto/CommunityCommentResponseDto.java
> 🩹 fix : dto 변경

- src/main/java/com/sparta/publicclassdev/domain/communities/component/CleanUpScheduler.java
- src/main/java/com/sparta/publicclassdev/domain/communities/controller/CommunitiesController.java
- src/main/java/com/sparta/publicclassdev/domain/communities/dto/CommunitiesRankDto.java
- src/main/java/com/sparta/publicclassdev/domain/communities/dto/CommunitiesRequestDto.java
- src/main/java/com/sparta/publicclassdev/domain/communities/dto/CommunitiesResponseDto.java
- src/main/java/com/sparta/publicclassdev/domain/communities/dto/CommunitiesUpdateRequestDto.java
- src/main/java/com/sparta/publicclassdev/domain/communities/entity/Communities.java
- src/main/java/com/sparta/publicclassdev/domain/communities/repository/CommunitiesRepository.java
- src/main/java/com/sparta/publicclassdev/domain/communities/service/CommunitiesService.java
- src/main/java/com/sparta/publicclassdev/domain/communitycomments/entity/CommunityComments.java
- src/main/java/com/sparta/publicclassdev/domain/communitycomments/repository/CommunityCommentsRepository.java
- src/main/java/com/sparta/publicclassdev/domain/communitycomments/service/CommunityCommentsService.java
- src/main/java/com/sparta/publicclassdev/domain/users/dto/ProfileResponseDto.java
- src/main/java/com/sparta/publicclassdev/domain/users/dto/UpdateProfileResponseDto.java
- src/main/java/com/sparta/publicclassdev/domain/users/service/UsersService.java
없음
> community -> communties로 패키지 명 변경
>
> 🩹 fix : community package명 변경

- src/main/java/com/sparta/publicclassdev/domain/communities/service/CommunitiesService.java
- src/main/java/com/sparta/publicclassdev/global/config/WebMvcConfig.java
> 🩹 fix : dto 수정

- src/main/java/com/sparta/publicclassdev/domain/users/dto/ProfileResponseDto.java
> #이슈번호
> Close #102 
> 프로필에 role 추가
>
> [2024-08-02] fix/#102-add-role-to-profile >> 프로필에 role 추가

- src/main/java/com/sparta/publicclassdev/domain/coderuns/controller/CodeRunsController.java
- src/main/java/com/sparta/publicclassdev/domain/coderuns/dto/CodeRunsResponseDto.java
- src/main/java/com/sparta/publicclassdev/domain/coderuns/entity/CodeRuns.java
- src/main/java/com/sparta/publicclassdev/domain/coderuns/service/CodeRunsService.java
> - CodeRuns 서비스, 컨트롤러 문제로 프론트에서 동작을 안해 리펙토링
>
> 코드실행 프론트에서 구동을 위한 리펙토링

- src/main/java/com/sparta/publicclassdev/domain/codereview/service/CodeReviewsService.java
- src/main/java/com/sparta/publicclassdev/domain/codereviewcomment/service/CodeReviewCommentsService.java
- src/main/java/com/sparta/publicclassdev/domain/coderuns/runner/PythonCodeRunner.java
> #108
> Close #108
> - 코드리뷰 기능 권한 검증 수정
> [2024-08-05] fix/#108 코드리뷰 기능 권한 검증 수정

- src/main/java/com/sparta/publicclassdev/domain/communities/entity/Communities.java
- src/main/java/com/sparta/publicclassdev/domain/communities/service/CommunitiesService.java
#110 
>  fix : admin 권한도 삭제/수정 가능하도록 변경
>
> 🩹 fix : admin 권한도 삭제/수정 가능하도록 변경

- src/main/java/com/sparta/publicclassdev/domain/codekatas/entity/CodeKatas.java
- src/main/java/com/sparta/publicclassdev/domain/coderuns/entity/CodeRuns.java
- src/main/java/com/sparta/publicclassdev/domain/coderuns/service/CodeRunsService.java
> 코드카타 삭제 시 연관관계 재설정

- src/main/java/com/sparta/publicclassdev/domain/winners/repository/WinnersRepository.java
> -🩹 fix : 오늘의 코드카타 삭제 시 발생하는 연관관계 오류 수정
>
> 🩹 fix : 오늘의 코드카타 삭제 시 발생하는 연관관계 오류 수정

- src/main/java/com/sparta/publicclassdev/domain/users/controller/UsersController.java
- src/main/java/com/sparta/publicclassdev/domain/users/service/UsersService.java
- src/main/java/com/sparta/publicclassdev/global/config/CacheConfig.java
> #이슈번호
> Close #118 
> 장시간 서버를 종료하고 방치했을 때 발생하는 토큰 재발급 문제 해결
>
> [2024-08-07] fix/#118-reissue-token-fix >> 토큰 재발급 문제 해결

- src/main/java/com/sparta/publicclassdev/domain/codekatas/entity/CodeKatas.java
> #121 
> Close #121
> - 🩹 fix : codekata contents컬럼을 text로 변경
> 🩹 fix : codekata contents컬럼을 text로 변경

- src/main/java/com/sparta/publicclassdev/domain/communities/dto/CommunitiesRequestDto.java
#123 
Community Content 글자 제한 해제
>
> 🩹 fix : Community Content 글자 제한 해제

- src/main/java/com/sparta/publicclassdev/domain/communities/repository/CommunitiesRepository.java
- src/main/java/com/sparta/publicclassdev/domain/communities/service/CommunitiesService.java
#126 
🩹 fix : Community Content 보이는 순서 변경
>
> 🩹 fix : Community Content 보이는 순서 변경

- src/main/java/com/sparta/publicclassdev/domain/codereview/entity/CodeReviews.java
> #131 
> Close #131
> - CodeReviews 의 contest 필드 값을 text 형태로 저장하도록 변경
>
> [2024-08-08] refactor: CodeReviews 의 contest 필드 값을 text 형태로 저장하도록 변경

- src/main/java/com/sparta/publicclassdev/domain/coderuns/runner/JavaCodeRunner.java
- src/main/java/com/sparta/publicclassdev/domain/coderuns/runner/JavaScriptCodeRunner.java
- src/main/java/com/sparta/publicclassdev/domain/coderuns/runner/PythonCodeRunner.java
- src/main/java/com/sparta/publicclassdev/global/exception/ErrorCode.java
> #128 
> Close #128 
> - ♻️ refactor : 코드 실행 시 실행가능시간 제한, 금지 코드 추가
>
> ♻️ refactor : 코드 실행 시 실행가능시간 제한, 금지 코드 추가

- src/main/java/com/sparta/publicclassdev/domain/coderuns/runner/JavaCodeRunner.java
🩹 fix : java실행이 안되던 문제 해결
> -🩹 fix : java실행이 안되던 문제 해결
>
> 🩹 fix : java실행이 안되던 문제 해결

- src/main/java/com/sparta/publicclassdev/domain/communities/component/CleanUpScheduler.java
- src/main/java/com/sparta/publicclassdev/domain/communities/service/CommunitiesService.java
#135 
> 🩹 fix : CleanUpScheduler RedisTemplate<String, Object> 변경
>
> 🩹 fix : CleanUpScheduler RedisTemplate<String, Object> 변경

- src/main/resources/application.yml
> #137 
> Close #137 
> - Timezone Asia/Seoul로 명시
>
> [2024-08-08] refactor: Timezone Asia/Seoul로 명시

- src/main/java/com/sparta/publicclassdev/global/config/TimeConfig.java
> #137 
> Close #137
> - 시간대 Asia/Seoul 변경
>
> [2024-08-08] Refactor/#137 시간대 변경

- src/main/java/com/sparta/publicclassdev/domain/coderuns/controller/CodeRunsController.java
- src/main/java/com/sparta/publicclassdev/domain/coderuns/dto/CodeRunsRequestDto.java
- src/main/java/com/sparta/publicclassdev/domain/coderuns/runner/PythonCodeRunner.java
> 코드 입력 받트는 부분 Valid 추가

- src/main/java/com/sparta/publicclassdev/domain/teams/entity/TeamUsers.java
- src/main/java/com/sparta/publicclassdev/domain/teams/entity/Teams.java
- src/main/java/com/sparta/publicclassdev/domain/teams/service/TeamsService.java
> #142 
> Close #142 
> - 줄 맞춤 안맞던 부분 수정
> - 스케줄러 수정(우승자 선정 후 팀 삭제되도록)
> [Refactor] 팀 서비스 줄맞춤이 안되있던 부분 수정

- src/main/java/com/sparta/publicclassdev/domain/winners/controller/WinnersController.java
- src/main/java/com/sparta/publicclassdev/domain/winners/repository/WinnersRepository.java
- src/main/java/com/sparta/publicclassdev/domain/winners/service/WinnersService.java
- src/main/java/com/sparta/publicclassdev/global/exception/ErrorCode.java
> #145 
> Close #145 
> - 관리자가 우승자를 생성하거나 삭제할 수 있는 기능 추가
>
> [Feat] 우승자 생성과 삭제 기능 추가 #145

- src/test/java/com/sparta/publicclassdev/EmbeddedRedisConfig.java
- src/test/java/com/sparta/publicclassdev/domain/users/controller/UsersControllerTest.java
> #이슈번호
> Close #149 
> embeddedredis config의 생성자 수정
>
> [2024-08-12] fix/#149-embeddedredis-bean-fix >> embeddedredis bean 생성 안되는 에러 수정

- src/test/java/com/sparta/publicclassdev/EmbeddedRedisConfig.java
> #이슈번호
> Close #156 
> embeddedredis 한번만 실행하도록 해결
>
> [2024-08-13] test/#156-embedded-redis-fix >> embeddedredis 실행문제 해결

- src/test/java/com/sparta/publicclassdev/domain/codereviewcomment/CodeReviewCommentsServiceTest.java
> #117
> Close #117
> - 코드리뷰 테스트코드 수정
>
> [2024-08-13] Test/#117 코드리뷰 테스트코드 수정

- src/test/java/com/sparta/publicclassdev/global/security/JwtUtilTest.java
> #이슈번호
> Close #168 
> JwtUtil 단위테스트 구현
>
> [2024-08-17] test/#168-JwtUtil-unittest >> JwtUtil 단위테스트 구현
